import configparser
import click
import os

CONFIGURATION_APPLICATION_PATH = click.get_app_dir('malabar')
CONFIGURATION_FILE_NAME        = os.path.join(CONFIGURATION_APPLICATION_PATH, 'configuration.ini')
DEFAULT_GROUP                  ='otec'

RSS_DATABASE_FILE_PATH         = os.path.join(CONFIGURATION_APPLICATION_PATH, 'rss.db')
OTEC_TEMPLATE_RSS_URI          = "http://cdafactory.pqa-collab.fr.alcatel-lucent.com/rss.php"

class OtecCfg:
        def __init__(self, sfile, _interpolation):
                self.configparser = configparser.ConfigParser(interpolation=_interpolation)
                print(sfile)
                self.configparser.read(sfile)

        def getDefaultSettings(self):
                return self.getSettings(DEFAULT_GROUP)

        def getSettings(self, group):
                return self.configparser[group]


def get_configuration(config_file_name, interpolation=configparser.BasicInterpolation()):
        return OtecCfg(config_file_name, interpolation)


def create_default_config_file():
    configparser = configparser.ConfigParser(allow_no_value = True, interpolation=None)
    configparser.add_section(DEFAULT_GROUP)
    configparser.set(DEFAULT_GROUP, '; This should be a comment! ;-)')
    configparser.set(DEFAULT_GROUP, '; Warning autogenerated file, Must be reviewed')
    configparser.set(DEFAULT_GROUP, host, 'bull6-05.fr.alcatel-lucent.com')
    configparser.set(DEFAULT_GROUP, user, 'root')
    configparser.set(DEFAULT_GROUP, password, 'letacla')
    configparser.set(DEFAULT_GROUP, rss-uri, OTEC_TEMPLATE_RSS_URI)
    configparser.set(DEFAULT_GROUP, 'enabled', 'false')
    configparser.add_section('SystemUnderTest')
    if not os.path.exists(CONFIGURATION_APPLICATION_PATH):
        os.makedirs(CONFIGURATION_APPLICATION_PATH)
    with open(CONFIGURATION_FILE_NAME, 'wb') as configfile:
        configparser.write(configfile)
